#!/bin/bash
set -euo pipefail
if command -v python >/dev/null 2>&1; then
  exec python "$@"
elif command -v python3 >/dev/null 2>&1; then
  exec python3 "$@"
else
  echo "NO_PYTHON_FOUND"
  exit 127
fi
